export const MODULES = [
  { name: "Products", perms: ["Read", "Create", "Update", "Delete", "Import", "Export"] },
  { name: "Categories", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Brands", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Warehouses", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Stores", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Stock In Logs", perms: ["Read", "Create", "Update"] },
  { name: "Purchase Orders", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Customer Purchase Orders", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Expense Listing", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Expense Categories", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Expense Budget Management", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Sales Report", perms: ["Read"] },
  { name: "Expense Report", perms: ["Read"] },
  { name: "Customers", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Agents", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Users", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Roles & Permissions", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Discounts", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Dashboard", perms: ["Read"] },
  { name: "System Logs", perms: ["Read"] },
  { name: "Payments Monitoring", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Deliveries Monitoring", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Quotations", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Statement of Accounts", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Credit Card Transactions", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Credit Card Transactions Report", perms: ["Read"] },
  { name: "Royalty Fees", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Financial Statement of Accounts", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Financial Royalty Fees", perms: ["Read", "Create", "Update", "Delete"] },
  { name: "Financial Credit Card Transactions", perms: ["Read", "Create", "Update", "Delete"] },
];